# Generated by Django 4.1.1 on 2022-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
